apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-02-10T23:28:16Z"
  name: phone-ui-service-jenkins
  namespace: default
  resourceVersion: "3867331"
  uid: d563068d-d459-424c-bfdc-be11d5bec053
spec:
  clusterIP: 10.108.83.239
  clusterIPs:
  - 10.108.83.239
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32256
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phone-ui-jenkins
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
