apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-ui-jenkins
spec:
  selector:
    matchLabels:
      app: phone-ui-jenkins
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 0
  template:
    metadata:
     labels:
      app: phone-ui-jenkins
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker-node2
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker-node2
      containers:
        - name: container-phone-ui-jenkins
          image: fatmakocabas/phone-ui:v4
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      #nodeSelector:
       # kubernetes.io/hostname: worker-node2
