apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phone-api
  template:
    metadata:
      labels:
        app: phone-api
    spec:
      containers:
        - name: phone-api
          image: fatmakocabas/phone-api:v2
          ports:
            - containerPort: 80 
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"

