apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-02-10T23:14:34Z"
  name: phone-api-service
  namespace: default
  resourceVersion: "3865654"
  uid: a8905c75-20be-4848-995d-aa17ae018ce0
spec:
  clusterIP: 10.101.183.95
  clusterIPs:
  - 10.101.183.95
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31717
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phone-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
