apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql-jenkins
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
      - name: mssql-jenkins
        image: mcr.microsoft.com/mssql/rhel/server:2019-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "trdh=sQQxdrao"
        volumeMounts:
        - name: mssqldb
          mountPath: /mssql
      volumes:
      - name: mssqldb
#        persistentVolumeClaim:
#          claimName: mssql-data-pvc
        hostPath:
          path: /root/mssql
