apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-02-10T21:53:54Z"
  name: mssql-service
  namespace: default
  resourceVersion: "3855821"
  uid: a18e3a24-56b0-4952-ae02-038aa7cff107
spec:
  clusterIP: 10.99.28.56
  clusterIPs:
  - 10.99.28.56
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31348
    port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: mssql
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
